// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjR-5D4yIYDAb1t5ii9ZaZ2XxVrSXInA',
    appId: '1:35313822795:web:31c67ef6a7fdaf846af1ce',
    messagingSenderId: '35313822795',
    projectId: 'beta-ai-bbc28',
    authDomain: 'beta-ai-bbc28.firebaseapp.com',
    storageBucket: 'beta-ai-bbc28.firebasestorage.app',
    measurementId: 'G-D2BZSVKY8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDukK3OgGN6UBoCWHExF-ysn5bcEBtrh70',
    appId: '1:35313822795:android:472c6b21c8e1a6796af1ce',
    messagingSenderId: '35313822795',
    projectId: 'beta-ai-bbc28',
    storageBucket: 'beta-ai-bbc28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKMABRdmRfLr_vL1yiD5Bdci5pU_NL5hY',
    appId: '1:35313822795:ios:41daf3ab352795ea6af1ce',
    messagingSenderId: '35313822795',
    projectId: 'beta-ai-bbc28',
    storageBucket: 'beta-ai-bbc28.firebasestorage.app',
    iosBundleId: 'com.example.voiceOrbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKMABRdmRfLr_vL1yiD5Bdci5pU_NL5hY',
    appId: '1:35313822795:ios:41daf3ab352795ea6af1ce',
    messagingSenderId: '35313822795',
    projectId: 'beta-ai-bbc28',
    storageBucket: 'beta-ai-bbc28.firebasestorage.app',
    iosBundleId: 'com.example.voiceOrbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqjR-5D4yIYDAb1t5ii9ZaZ2XxVrSXInA',
    appId: '1:35313822795:web:381323912c7d50d46af1ce',
    messagingSenderId: '35313822795',
    projectId: 'beta-ai-bbc28',
    authDomain: 'beta-ai-bbc28.firebaseapp.com',
    storageBucket: 'beta-ai-bbc28.firebasestorage.app',
    measurementId: 'G-DPFEHSF3F3',
  );
}
